### ISSUE TITLE
Span causes aloha to not unwrap elements

### ISSUE THREAD

**Issue by mouse0270** [alohaeditor/Aloha-Editor#1372]
The following example causes aloha to not unwrap elements when changing them from a header 1 to a header 2 but instead causes it just appends a header 2 within a header1

``` html
<span class="editable">
  <h1>I am a really big header</h1>
</span>
``` 
If you change the header 1 tag to a header 2 tag you get this
``` html
<span class="editable">
  <h1>
    <h2>I am a really big header</h2>
  </h1>
</span>
```
But if you use a div it seems to work, why is this?
``` html
<div class="editable">
  <h1>I am a really big header</h1>
</div>
```

**Comment by mouse0270** [comment]
In all honesty this really probably shouldn't be fixed because you shouldn't wrap a header in a span, but it should be stated that you should use a div

**Comment by petrosalema** [comment]
It's curious that this behavior exists, but it is not surprising that broken markup would lead to unexpected behavior. We don't explicitly state this for each function, because we assume it. Aloha Editor operates on valid HTML DOM, all else is undefined behavior.

As I pondered it (without looking at code), I imagine that Aloha notices that it cannot place an ```H2``` inside of the ```span``` but since it is possible to do so inside the (already illegal) ```H1```, it does so.

Helpful code snippet:

```javascript
aloha.content.allowsNesting('span', 'h1')
```

Helpful API point:
http://www.alohaeditor.org/api/content.html#allowsNesting
